#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# Lumo TTY3 autostart
if [[ "$(tty)" = "/dev/tty3" ]] && [[ -z "$WAYLAND_DISPLAY" ]] && [[ -z "$DISPLAY" ]]; then
    exec ~/Projects/lumo-shell/scripts/lumo-tty.sh
fi
