#
# ~/.bash_profile
#

# W31.6: clear console ASAP pra cobrir agetty autologin welcome
clear
printf "\033[?25l"  # hide cursor

[[ -f ~/.bashrc ]] && . ~/.bashrc

# Lumo TTY3 autostart
if [[ "$(tty)" = "/dev/tty3" ]] && [[ -z "$WAYLAND_DISPLAY" ]] && [[ -z "$DISPLAY" ]]; then
    exec ~/Projects/lumo-shell/scripts/lumo-tty.sh
fi
