[workspace]
resolver = "2"
members = [
    "shell",
    "crates/foundation/lumo-foundation",
    "crates/graphics/lumo-beam",
    "crates/graphics/lumo-graphics",
    "crates/graphics/lumo-text",
    "crates/graphics/lumo-animation",
    "crates/ui/lumo-input",
    "crates/ui/lumo-kit",
    "crates/compositor/lumo-wm",
    "crates/compositor/lumo-ipc",
    "crates/lumo-gfx-core",
    "crates/system/lumo-sensors",
    "crates/cli/lumoctl",
    "apps/lumo-files",
]

[profile.release]
lto = "thin"
codegen-units = 16

[patch.crates-io]
smithay = { path = "vendor/smithay" }

[workspace.metadata]
# vendor smithay patched for sRGB8_ALPHA8 import (A17)
