[workspace]
resolver = "2"
members = [
    "shell",
    "crates/foundation/lumo-foundation",
    "crates/foundation/lumo-style",
    "crates/foundation/lumo-telemetry",
    "crates/foundation/lumo-error",
    "crates/lumo-decor",
    "crates/graphics/lumo-beam",
    "crates/graphics/lumo-graphics",
    "crates/graphics/lumo-text",
    "crates/graphics/lumo-animation",
    "crates/ui/lumo-input",
    "crates/ui/lumo-kit",
    "crates/ui/lumo-osd-framework",
    "crates/compositor/lumo-wm",
    "crates/compositor/lumo-ipc",
    "crates/lumo-gfx-core",
    "crates/system/lumo-sensors",
    "crates/cli/lumoctl",
    "apps/lumo-files",
    "apps/lumo-term",
    "apps/lumo-dock",
    "apps/lumo-launcher",
    "apps/lumo-notif",
    "apps/lumo-clip",
    "apps/lumo-settings",
    "apps/lumo-editor",
    "apps/lumo-calc",
    "apps/lumo-notes",
    "apps/lumo-monitor",
    "apps/lumo-lock",
    "apps/lumo-firstrun",
    "apps/lumo-store",
    "apps/lumo-bridge",
    "apps/lumo-about",
    "apps/lumo-apps",
    "apps/lumo-appsd",
    "apps/lumo-appctl",
    "apps/lumo-osd-locks",
    "apps/lumo-osd-brightness",
    "apps/lumo-osd-volume",
]

[profile.release]
lto = "thin"
codegen-units = 16

[patch.crates-io]
smithay = { path = "vendor/smithay" }
winit = { path = "vendor/winit-0.30.13" }

users = { path = "vendor/users-shim" }

[workspace.metadata]
# vendor smithay patched for sRGB8_ALPHA8 import (A17)
